# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc553512213ab65de11aa7b53ce44122"
name = "branded-merchant-app"
handle = "branded-merchant-app-7"
application_url = "https://df45-2607-fea8-28e6-1d00-d188-50a4-1a8-65fc.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "umarttesting.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,write_draft_orders,write_purchase_options,read_inventory,write_inventory,read_orders"

[auth]
redirect_urls = [
  "https://df45-2607-fea8-28e6-1d00-d188-50a4-1a8-65fc.ngrok-free.app/auth/callback",
  "https://df45-2607-fea8-28e6-1d00-d188-50a4-1a8-65fc.ngrok-free.app/auth/shopify/callback",
  "https://df45-2607-fea8-28e6-1d00-d188-50a4-1a8-65fc.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
